#!/bin/bash

function usage {
  echo "Incorrect Arugments"
  echo "$0 [DOMAIN] [PORT] [HOST] [PROTOCOL] [NUM_THREADS] [LOG_PREFIX]"
  exit 1
}

if [[ $# -ne 6 ]]; 
      then usage
fi

domain=$1
port=$2
host=$3
protocol=$4
num_threads=$5
log_prefix=$6


jmeter -n -t gormeter-general.jmx \
  -Jnum_threads=$num_threads \
  -Jnum_loops=$((80000/$num_threads)) \
  -Jdomain=$domain \
  -Jport=$port \
  -Jhost=$host \
  -Jprotocol=$protocol \
  -l ./out/${log_prefix}_gormeter_${protocol}_${num_threads}t_`date +%s`.log
