#!/bin/bash

function usage {
  echo "Incorrect Arugments"
  echo "$0 [DOMAIN] [PORT] [HOST] [PROTOCOL] [KEEP_ALIVE] [LOG_PREFIX]"
  exit 1
}

if [[ $# -ne 6 ]]; 
      then usage
fi

domain=$1
port=$2
host=$3
protocol=$4
keep_alive=$5
log_prefix=$6

if [$keep_alive = "true"]
then
  alive_flag="keepAlive"
else  
  alive_flag="closeConn"
fi

num_threads=(10 25 50 100)

for num_thread in ${num_threads[*]}; do 
    jmeter -n -t gormeter-general.jmx \
      -Jnum_threads=$num_thread \
      -Jnum_loops=$((10000/$num_thread)) \
      -Jdomain=$domain \
      -Jport=$port \
      -Jhost=$host \
      -Jkeep_alive=$keep_alive \
      -Jprotocol=$protocol \
      -l ./out/${log_prefix}_gormeter_${protocol}_${alive_flag}_${num_thread}t_`date +%s`.log
done
